server:
  port: 8082

spring:
  application:
    name: customer
  data:
    mongodb:
      database: customer
      uri: mongodb://localhost:27017/customer

management:
  server:
    address: 0.0.0.0
  security:
    enabled: false
  endpoint:
    health:
      show-details: always
    web:
      exposure:
        include: info, health, mappings

